// ---------------------------------------------------------------------------
// GBNF grammar generator for `.wd` DIRECTIVE LINES.
//
// `generateGrammar()` emits a llama.cpp-compatible GBNF grammar that constrains
// a small model's decoding to well-formed Darkmown directive lines (plus the
// `{ path | pipe }` interpolation token). It is generated from the SAME catalog
// the cheatsheet uses, so the keyword set, `@loop` clauses, comparison operators,
// and format-pipe names can never drift from what compiles.
//
// Scope (stated deliberately): this grammar constrains the SHAPE of a directive
// line — the leading keyword must be a real directive, `@loop` must be
// `@loop <src> into <item> …clauses`, a `where`/`:if` condition must be
// `operand <op> operand`, a `:button` must be `"…" -> <action-chain>`, and an
// interpolation must pipe through a known formatter. It does NOT try to grammar-
// check free-form values (arbitrary JSON seeds, URLs, prose) — those are `text`.
// That is enough to delete the on-device failure class (JS/HTML muscle-memory
// openers like `::: card class=` or `cart.filter(...)` become unrepresentable)
// while staying small and maintainable.
// ---------------------------------------------------------------------------

import { CATALOG_ACTION_GRAMMAR, directiveCatalog } from "./catalog.js";

/** Slugify a directive token into a GBNF rule name (`@loop` → `dir-loop`). */
/** @type {Record<string, string>} */
const SLUG = {
  "@include": "dir-include",
  "@loop": "dir-loop",
  ":::": "dir-container",
  ":if": "dir-if",
  ":state": "dir-state",
  ":store": "dir-store",
  ":computed": "dir-computed",
  ":fetch": "dir-fetch",
  ":effect": "dir-effect",
  ":every": "dir-every",
  ":theme": "dir-theme",
  ":button": "dir-button",
  ":form": "dir-form",
  ":input": "dir-input",
  ":textarea": "dir-textarea",
  ":select": "dir-select",
  ":checkbox": "dir-checkbox",
  ":radio": "dir-radio",
  ":submit": "dir-submit",
  ":bind": "dir-bind",
  ":slider": "dir-slider",
  ":video": "dir-video",
  ":audio": "dir-audio",
  ":embed": "dir-embed",
  ":carousel": "dir-carousel"
};

// The directives given a structured RHS below; every other directive gets the
// generic `"<keyword>" restofline` rule (keyword pinned, argument tail free).
const STRUCTURED = new Set(["@loop", ":if", ":button", ":::"]);

/** A GBNF alternation literal list, e.g. `"a" | "b"`. */
const alt = (/** @type {string[]} */ items) => items.map((s) => `"${s}"`).join(" | ");

/**
 * One alternative of the `action-op` rule, from a catalog action's shape.
 * `name++` (suffix, no space) vs `name toggle [v]` / `name append v` (infix).
 * @param {{ token: string, place: "suffix" | "infix", operand: "none" | "required" | "optional" }} op
 * @returns {string}
 */
function actionAlternative({ token, place, operand }) {
  if (place === "suffix") return `"${token}"`;
  const tail =
    operand === "required" ? " sp value" : operand === "optional" ? " ( sp value )?" : "";
  return `sp "${token}"${tail}`;
}

/**
 * Generate the GBNF grammar for `.wd` directive lines from the directive catalog.
 * @returns {string}
 */
export function generateGrammar() {
  const cat = directiveCatalog();
  const dirRules = cat.directives.map((d) => SLUG[d.name]).filter(Boolean);

  /** @type {string[]} */
  const lines = [];
  lines.push("# Darkmown .wd directive-line grammar — generated by src/grammar.js");
  lines.push(
    "# Constrains a directive line (or a { path | pipe } interpolation). Do not edit by hand."
  );
  lines.push("");
  // A `.wd` line is an opener, a BLOCK CLOSER (or mid-block marker), or an
  // interpolation. The closers were missing, so constrained decoding could open
  // an `@loop` it was then unable to close.
  lines.push("root ::= directive | closer | binding");
  lines.push(`directive ::= ${dirRules.join(" | ")}`);
  lines.push(
    'closer ::= "@endloop" | "@empty" | ":endif" | ":endform" | ":endcarousel" | ":::"' +
      ' | ":else if" sp condition ( sp joiner sp condition )* | ":else if" sp path | ":else"'
  );
  lines.push("");

  // Structured directives.
  lines.push('dir-loop ::= "@loop" sp operand sp "into" sp ident loop-clauses');
  lines.push('dir-if ::= ":if" sp ( condition (sp joiner sp condition)* | path )');
  // The label, then the accessibility attributes the compiler whitelists, then
  // the arrow. Attributes are OPTIONAL and repeatable; the whitelist is spelled
  // out here (rather than left to `restofline`) so a constrained model can emit
  // `role`/`aria-…`/`title` and cannot invent `onclick=` or `class=`.
  lines.push('dir-button ::= ":button" sp dqstring ( sp a11y-attr )* sp "->" sp action-chain');
  lines.push('dir-container ::= ":::" restofline');
  lines.push("");

  // Generic directives: keyword pinned, argument tail free to end of line.
  for (const d of cat.directives) {
    if (STRUCTURED.has(d.name)) continue;
    lines.push(`${SLUG[d.name]} ::= "${d.name}" restofline`);
  }
  lines.push("");

  // @loop clause vocabulary (mirrors the fixed clause order in the catalog).
  // `sort by`, `offset` and `limit` each accept a REACTIVE form as well as a
  // literal — `sort by { sortKey } { sortDir }` for clickable-header sort, and
  // `limit pageSize` for a state-driven page size. The grammar used to allow
  // only the literal form, which made those shipped features unreachable under
  // constrained decoding.
  lines.push("loop-clauses ::= ( sp loop-clause )*");
  lines.push(
    'loop-clause ::= where-clause | "sort by" sp sort-key ( sp sort-dir )? | "reverse"' +
      ' | "offset" sp count | "limit" sp count | "paginate" sp number | "sortable"'
  );
  lines.push("sort-key ::= path | statebinding");
  lines.push('sort-dir ::= "asc" | "desc" | statebinding');
  lines.push("count ::= number | ident");
  lines.push('statebinding ::= "{" wsopt ident wsopt "}"');
  lines.push('where-clause ::= "where" sp condition ( sp joiner sp condition )*');
  // A leading `not` negates one condition (it is a PREFIX, not a joiner — the
  // catalog lists it under predicateJoiners, so it is derived from there rather
  // than filtered away).
  const negate = cat.predicateJoiners.includes("not") ? '( "not" sp )? ' : "";
  lines.push(`condition ::= ${negate}operand sp op sp operand`);
  lines.push(`op ::= ${alt(cat.predicateOps.map((o) => o.name))}`);
  lines.push(`joiner ::= ${alt(cat.predicateJoiners.filter((j) => j !== "not"))}`);
  lines.push("");

  // Button-action vocabulary, DERIVED from the catalog's action ops (token +
  // shape) so the grammar cannot list a different set from `llms.txt` and the
  // `WD311` hint. It used to be one hand-written string; that is how `refetch`
  // ended up in the grammar and nowhere else.
  lines.push('action-chain ::= action ( wsopt ";" wsopt action )*');
  lines.push("action ::= ident action-op");
  lines.push(`action-op ::= ${CATALOG_ACTION_GRAMMAR.map(actionAlternative).join(" | ")}`);
  lines.push("");

  // Interpolation binding with format pipes.
  lines.push('binding ::= "{" wsopt path pipe-chain wsopt "}"');
  lines.push('pipe-chain ::= ( wsopt "|" wsopt pipe ( ":" value )* )*');
  lines.push(`pipe ::= ${alt(cat.formatPipes.map((p) => p.name))}`);
  lines.push("");

  // Accessibility attributes (`::: ` headers and `:button` share the whitelist).
  lines.push('a11y-attr ::= a11y-name "=" dqstring');
  lines.push('a11y-name ::= "role" | "title" | "aria-" [a-z] [a-z0-9-]*');
  lines.push("");

  // Terminals.
  lines.push("operand ::= path | dqstring | number");
  lines.push("value ::= dqstring | number | path");
  lines.push("ident ::= [a-zA-Z_$] [a-zA-Z0-9_$]*");
  lines.push("path ::= [a-zA-Z0-9_$/.~-]+");
  lines.push("number ::= [0-9]+");
  lines.push('dqstring ::= "\\"" [^"]* "\\""');
  lines.push("restofline ::= [^\\n]*");
  lines.push('sp ::= " "+');
  lines.push('wsopt ::= " "*');
  lines.push("");
  return lines.join("\n");
}
